version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: sms_db
      MYSQL_USER: jerry
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    networks:
      - sms_network

  sms-server:
    build:
      context: ./sms-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - sms_network
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sms_db
      SPRING_DATASOURCE_USERNAME: jerry
      SPRING_DATASOURCE_PASSWORD: admin1234
    links:
      - mysql

  sms-client:
    build:
      context: ./sms-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - sms_network
    depends_on:
      - sms-server

networks:
  sms_network:
    driver: bridge
