apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-server
  template:
    metadata:
      labels:
        app: sms-server
    spec:
      containers:
      - name: sms-server
        image: siddhantbhattarai/react-springboot-sms-server
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/sms_db
        - name: SPRING_DATASOURCE_USERNAME
          value: jerry
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin1234
---
apiVersion: v1
kind: Service
metadata:
  name: sms-server-service
spec:
  selector:
    app: sms-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
