server:
  port: 8080

spring:
  datasource:
    username: jerry
    password: admin1234
    url: jdbc:mysql://mysql:3306/sms_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
