spring:
  datasource:
    username: jerry
    password: admin1234
    url: jdbc:mysql://mysql_db:3306/sms_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
